name: Dynamic Matrix Workflow

on:
  push:
    branches:
      - ci/test-automation

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Geun-Oh/terraform-provider-ncloud' }}
    outputs:
      dynamic-matrix: ${{ steps.convert-to-json.outputs.matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Convert YAML to JSON
        id: convert-to-json
        run: |
          json_output=$(yq eval -o=json .github/data/region.yml)
          matrix_json=$(echo $json_output | jq -c '.')
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT

  call-workflow:
    needs: prepare-matrix
    strategy:
      fail-fast: false
      matrix:
        region_service: ${{ fromJSON(needs.prepare-matrix.outputs.dynamic-matrix) }}
    uses: ./.github/workflows/execute.yml
    with:
      agent: ${{ matrix.region_service.service }}
      region: ${{ matrix.region_service.region }}
      zone: ${{ matrix.region_service.zone }}
    secrets:
      access_key: ${{ secrets.NCLOUD_ACCESS_KEY }}
      secret_key: ${{ secrets.NCLOUD_SECRET_KEY }}
