name: Test Scheduler

# on:
#     schedule:
#         - cron:  "0 0 * * *"

on:
    push:
        branches: 
            - "main"
            - "ci/test-automation"

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: ["1.21"]
                agent: ["obs_vpc_agent", "server_redis_agent"]  # 5개의 에이전트
                include:
                    - agent: "obs_vpc_agent"
                      tests: "objectstorage vpc"  # 1번 에이전트가 순차적으로 실행할 테스트 리스트
                    - agent: "server_redis_agent"
                      tests: "server redis"  # 2번 에이전트가 실행할 테스트
                    # - agent: 3
                    #   tests: "TestIndependentSuite3 TestIndependentSuite4"  # 3번 에이전트가 실행할 테스트
                    # - agent: 4
                    #   tests: "TestIndependentSuite5 TestIndependentSuite6"  # 4번 에이전트가 실행할 테스트
                    # - agent: 5
                    #   tests: "TestIndependentSuite7 TestIndependentSuite8"  # 5번 에이전트가 실행할 테스트

        steps:
          - name: checkout branch
            uses: actions/checkout@v4
    
          - name: Set up Go
            uses: actions/setup-go@v5
            with:
              go-version: ${{ matrix.go-version }}
              cache: false

          - name: Install AWS CLI
            run: |
              sudo apt-get update
              sudo apt-get install -y awscli
    
          - name: Configure AWS CLI with NCP S3 compatible endpoint
            run: |
              aws configure set aws_access_key_id ${{ secrets.NCP_ACCESS_KEY_ID }}
              aws configure set aws_secret_access_key ${{ secrets.NCP_SECRET_ACCESS_KEY }}
              aws configure set region kr-standard
              aws configure set s3.endpoint_url https://kr.object.ncloudstorage.com

          - name: Install ctrf cli tool
            run: |
                go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
    
          - name: Run tests on agent ${{ matrix.agent }}
            run: |
                echo "Running tests on agent ${{ matrix.agent }}"
                for test in ${{ matrix.tests }}; do
                    export TF_ACC=1
                    export NCLOUD_REGION=${{ secrets.NCLOUD_REGION }}
                    export NCLOUD_ACCESS_KEY=${{ secrets.NCLOUD_ACCESS_KEY }}
                    export NCLOUD_SECRET_KEY=${{ secrets.NCLOUD_SECRET_KEY }}
                    echo $PWD
                    echo $ls
                    echo "$test"
                    go test -timeout 2h -v -json ./internal/service/"$test" | go-ctrf-json-reporter -output "$test"-report.json
                    cat "$test"-report.json

                    aws --endpoint-url=https://kr.object.ncloudstorage.com s3 cp "$test"-report.json s3://test-dashboard/data/"$test"-report.json
                done
